class SoundSystem {
    constructor() { this.ctx = null; this.masterGain = null; this.bgmTimer = null; this.isMuted = false; this.isInit = false; }
    init() { if (this.isInit) return; try { const AudioContext = window.AudioContext || window.webkitAudioContext; this.ctx = new AudioContext(); this.masterGain = this.ctx.createGain(); this.masterGain.gain.value = 0.3; this.masterGain.connect(this.ctx.destination); this.isInit = true; this.startBGM(); } catch (e) { console.log("Audio not supported"); } }
    toggleMute() { this.isMuted = !this.isMuted; if (this.masterGain) this.masterGain.gain.value = this.isMuted ? 0 : 0.3; document.getElementById('sound-toggle').innerText = this.isMuted ? '🔇' : '🔊'; }
    playTone(freq, type, duration, startTime = 0, vol = 1) { if (!this.isInit || this.isMuted) return; const osc = this.ctx.createOscillator(); const gain = this.ctx.createGain(); osc.type = type; osc.frequency.setValueAtTime(freq, this.ctx.currentTime + startTime); gain.gain.setValueAtTime(vol, this.ctx.currentTime + startTime); gain.gain.exponentialRampToValueAtTime(0.01, this.ctx.currentTime + startTime + duration); osc.connect(gain); gain.connect(this.masterGain); osc.start(this.ctx.currentTime + startTime); osc.stop(this.ctx.currentTime + startTime + duration); }
    playNoise(duration, vol = 1) { if (!this.isInit || this.isMuted) return; const bufferSize = this.ctx.sampleRate * duration; const buffer = this.ctx.createBuffer(1, bufferSize, this.ctx.sampleRate); const data = buffer.getChannelData(0); for (let i = 0; i < bufferSize; i++) data[i] = Math.random() * 2 - 1; const noise = this.ctx.createBufferSource(); noise.buffer = buffer; const gain = this.ctx.createGain(); gain.gain.setValueAtTime(vol, this.ctx.currentTime); gain.gain.exponentialRampToValueAtTime(0.01, this.ctx.currentTime + duration); noise.connect(gain); gain.connect(this.masterGain); noise.start(); }
    click() { this.playTone(800, 'sine', 0.1); }
    shoot(type) { if (type === 'LASER') { const osc = this.ctx.createOscillator(); const gain = this.ctx.createGain(); osc.frequency.setValueAtTime(800, this.ctx.currentTime); osc.frequency.exponentialRampToValueAtTime(100, this.ctx.currentTime + 0.1); gain.gain.setValueAtTime(0.3, this.ctx.currentTime); gain.gain.exponentialRampToValueAtTime(0.01, this.ctx.currentTime + 0.1); osc.connect(gain); gain.connect(this.masterGain); osc.start(); osc.stop(this.ctx.currentTime + 0.1); } else if (type === 'SHOTGUN') { this.playNoise(0.15, 0.7); this.playTone(100, 'sawtooth', 0.1, 0, 0.5); } else if (type === 'SHOCKWAVE') { this.playTone(200, 'sine', 0.3, 0, 0.5); } else { this.playTone(150, 'square', 0.15, 0, 0.5); this.playNoise(0.1, 0.3); } }
    explode() { this.playNoise(0.4, 0.6); this.playTone(100, 'sawtooth', 0.3, 0, 0.4); }
    pickup() { this.playTone(1200 + Math.random() * 400, 'sine', 0.15, 0, 0.4); }
    levelUp() { this.playTone(523.25, 'square', 0.2, 0, 0.5); this.playTone(659.25, 'square', 0.2, 0.1, 0.5); this.playTone(783.99, 'square', 0.2, 0.2, 0.5); this.playTone(1046.50, 'square', 0.6, 0.3, 0.5); }
    skillReady() { this.playTone(880, 'sine', 0.5, 0, 0.5); this.playTone(1760, 'sine', 0.5, 0.1, 0.3); }
    skillCast() { this.playNoise(0.5, 0.5); const osc = this.ctx.createOscillator(); const gain = this.ctx.createGain(); osc.frequency.setValueAtTime(200, this.ctx.currentTime); osc.frequency.linearRampToValueAtTime(800, this.ctx.currentTime + 0.5); gain.gain.setValueAtTime(0.5, this.ctx.currentTime); gain.gain.linearRampToValueAtTime(0, this.ctx.currentTime + 0.5); osc.connect(gain); gain.connect(this.masterGain); osc.start(); osc.stop(this.ctx.currentTime + 0.5); }
    reload() { this.playTone(400, 'square', 0.1, 0, 0.2); this.playTone(500, 'square', 0.1, 0.2, 0.2); }
    startBGM() { if (this.bgmTimer) return; let noteIndex = 0; const bassLine = [65.41, 65.41, 98.00, 98.00, 110.00, 110.00, 87.31, 87.31]; this.bgmTimer = setInterval(() => { if (this.isMuted || gameState !== 'PLAYING') return; const freq = bassLine[noteIndex % bassLine.length]; this.playTone(freq, 'sawtooth', 0.2, 0, 0.15); if (noteIndex % 4 === 0) this.playTone(freq * 4, 'square', 0.1, 0, 0.05); noteIndex++; }, 250); }
}

const audio = new SoundSystem();
function toggleSound() { audio.toggleMute(); }
