const ITEM_DB = {
    'act_overcharge': { type:'ACTIVE', name:'过载充能', desc:'大幅提升移速、攻速，并降低受到伤害。', cd:25, dur:6, effect:0.2, forge:['cd','dur','effect'], aim:false },
    'act_nitro': { type:'ACTIVE', name:'氮气加速', desc:'提供移速加成，期间无视任何碰撞伤害。', cd:20, dur:6, effect:0.4, forge:['cd','dur','effect'], aim:false },
    'act_repair': { type:'ACTIVE', name:'自我修复', desc:'在短时间内快速且持续地恢复生命值。', cd:20, dur:1.5, effect:0.02, forge:['cd','dur','effect'], aim:false },
    'act_fortify': { type:'ACTIVE', name:'加固防御', desc:'大幅降低受到的伤害，但移速会明显降低。', cd:30, dur:6, effect:0.6, forge:['cd','dur','effect'], aim:false },
    'act_radar': { type:'ACTIVE', name:'雷达屏蔽', desc:'进入无敌状态并无视碰撞，使所有敌人丢失目标。', cd:25, dur:4, effect:0, forge:['cd','dur'], aim:false },
    'act_wormhole': { type:'ACTIVE', name:'虫洞穿梭', desc:'拖动瞄准，延迟0.5秒后传送到指定区域。', cd:20, dur:0, effect:240, forge:['cd','effect'], aim:true },
    'act_orbital': { type:'ACTIVE', name:'轨道打击', desc:'拖动瞄准，延迟后对该区域进行毁灭性轰炸。', cd:50, dur:6, effect:1.0, speed:5, forge:['cd','dur','effect','speed'], aim:true },
    'act_shield': { type:'ACTIVE', name:'能量护盾', desc:'获得基于最大生命的护盾持续衰减，破裂时造成击退和反伤。', cd:40, dur:20, effect:0.5, forge:['cd','dur','effect'], aim:false },
    'pas_manual': { type:'PASSIVE', name:'驾驶手册', desc:'提升战场中的经验获得倍率。', stat:'xpMult', effect:0.05, forge:['effect'] },
    'pas_oil': { type:'PASSIVE', name:'机油', desc:'提升战车的移动速度。', stat:'speed', effect:0.05, forge:['effect'] },
    'pas_sight': { type:'PASSIVE', name:'瞄具', desc:'提升所有武器的射程。', stat:'range', effect:0.05, forge:['effect'] },
    'pas_powder': { type:'PASSIVE', name:'高爆火药', desc:'提升所有爆炸伤害的波及范围。', stat:'splash', effect:0.05, forge:['effect'] },
    'pas_plate': { type:'PASSIVE', name:'钢板', desc:'提升战车的最大生命值。', stat:'hp', effect:0.05, forge:['effect'] },
    'pas_ap': { type:'PASSIVE', name:'穿甲弹', desc:'提升所有武器的基础攻击力。', stat:'atk', effect:0.05, forge:['effect'] },
    'pas_spring': { type:'PASSIVE', name:'弹簧', desc:'提升武器的基础攻击速度。', stat:'atkSpd', effect:0.05, forge:['effect'] },
    'pas_magnet': { type:'PASSIVE', name:'吸铁石', desc:'大幅提升各种掉落物的拾取范围。', stat:'pickup', effect:0.10, forge:['effect'] },
    'pas_cone': { type:'PASSIVE', name:'圆锥桶', desc:'按百分比降低受到的碰撞伤害。', stat:'colDmg', effect:0.10, forge:['effect'] },
    'pas_charger': { type:'PASSIVE', name:'充电器', desc:'提升技能的能量上限。', stat:'energy', effect:0.10, forge:['effect'] },
    'pas_photo': { type:'PASSIVE', name:'光合模组', desc:'全面提升能量上限与能量恢复速度。', stat:'energyAll', effect:0.06, forge:['effect'] },
    'pas_atkmod': { type:'PASSIVE', name:'攻击模组', desc:'全面提升基础攻击力与攻击速度。', stat:'atkAll', effect:0.03, forge:['effect'] },
    'pas_defmod': { type:'PASSIVE', name:'防御模组', desc:'全面提升最大生命值并提供全伤减免。', stat:'defAll', effect:0.03, forge:['effect'] },
    'pas_calib': { type:'PASSIVE', name:'校准模组', desc:'全面提升武器射程与爆炸范围。', stat:'rangeAll', effect:0.03, forge:['effect'] },
    'pas_agile': { type:'PASSIVE', name:'灵巧模组', desc:'全面提升移动速度与子弹飞行速度。', stat:'spdAll', effect:0.03, forge:['effect'] },
    'pas_defiance': { type:'PASSIVE', name:'名刀', desc:'濒死时保留1点生命并获得无敌效果。', cd:60, dur:2.5, stat:'special', forge:['cd','dur'] },
    'pas_trinity': { type:'PASSIVE', name:'三项', desc:'施放技能后的短暂时间内提升全部伤害。', dur:3, effect:0.33, stat:'special', forge:['dur','effect'] },
    'pas_clover': { type:'PASSIVE', name:'三叶草', desc:'提升稀有掉落物(道具/补给)出现的概率。', stat:'luck', effect:0.05, forge:['effect'] },
    'pas_grit': { type:'PASSIVE', name:'气概', desc:'生命值越低，造成的伤害越高。', stat:'special', effect:0.4, forge:['effect'] }
};
